server:
  port: 0             # Port par défaut du serveur

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mokengeli_biloko_db
    username: user1
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 180000       # 3 minutes
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:                                      # Hibernate crée/mettre à jour les tables automatiquement
    properties:
      hibernate:
        default_schema: user_schema
        jdbc:
          time_zone: Europe/Paris # Pour l'interpretation du temps a enregistrer en base

  jackson:
    time-zone: Europe/Paris # Pour la serialisation du temps
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    fetch-registry: true  # Le client doit récupérer les services
    register-with-eureka: true  # Le client s'enregistre dans le registre
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP pour l'enregistrement (utile pour les environnements containerisés)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
security:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: 9a4f2c_8d3b7a1e6f#45c8a0b3f268b1d4e6-f3c8a9d2b5f8e3a9c8-b5f6v8a3d9A@
  is-ssl: false
logging:
  level:
    com.zaxxer.hikari: INFO


