server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: user-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${POSTGRES_SCHEMA:user_schema}
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 180000       # 3 minutes
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE:GMT+01:00}
  jackson:
    time-zone: ${TIME_ZONE:GMT+01:00}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  jwt:
    secret: ${JWT_SECRET}
    is-ssl: ${IS_SSL:false}