server:
  port: 0             # Port par défaut du serveur

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user1
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:                                      # Hibernate crée/mettre à jour les tables automatiquement
    show-sql: true                                          # Affiche les requêtes SQL générées dans la console
    properties:
      hibernate:
        default_schema: user_service_schema                 # Spécifie le schéma PostgreSQL à utiliser
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    fetch-registry: true  # Le client doit récupérer les services
    register-with-eureka: true  # Le client s'enregistre dans le registre
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP pour l'enregistrement (utile pour les environnements containerisés)




